### ISSUE TITLE
Can't run script; permission denied

### ISSUE THREAD

**Issue by 1nikolas** [airvzxf/cache-anything-new-action#2]
When I try to run the workflow, I get this error
```
# ----------------------------------------------------------
# ----------------------------------------------------------
# Init the user script
# ----------------------------------------------------------
/home/runner/work/_actions/airvzxf/cache-anything-new-action/v1.0/src/init.sh: line 31: /home/runner/work/<repo>/<repo>/.github/workflows/install.sh: Permission denied
Error: Process completed with exit code 126.
```

Maybe it needs to run `chmod +x` first?
Thanks in advance

**Comment by airvzxf** [comment]
Fixed in the commit 1c4a6b11259176b6a12d0989074f92b6c939295c.

> Note: In case this update fix the problem then close this issue, otherwise if I don't receive an answer in a couple of weeks, I'll close automatically.

**Comment by 1nikolas** [comment]
Problem fixed, thank you

**Comment by dasa2** [comment]
@1nikolas how did you fix it could you give the solution ?

**Comment by 1nikolas** [comment]
> @1nikolas how did you fix it could you give the solution ?

I think I had to chmod +x the script but I'm not sure it's been 4 years..

**Comment by airvzxf** [comment]
Hi, @dasa2. If your repository is public, I would review it? Please provide a link for the GitHub Action which marks the error.
